name: Store Repository Structure in MongoDB
on:
  # Trigger on push to any branch, including main
  push:
    branches:
      - '*'
      - main
    paths:
      - '/*.md'
      - '/*.jpg'
      - '/*.jpeg'
      - '/*.png'
      - '/*.mp4'
      - '/assets/**' # Correct wildcard for all files in assets

  # Trigger on pull request actions
  pull_request:
    types: 
      - opened
      - synchronize
      - reopened
      - closed
    paths:
      - '/*.md'
      - '/*.jpg'
      - '/*.jpeg'
      - '/*.png'
      - '/*.mp4'
      - '/assets/**'

  # Trigger when a specific repository event occurs
  repository_dispatch:
    types:
      - file_change
  
  # Daily schedule for backup
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight

jobs:
  storeRepoStructure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install PyGithub pymongo python-dotenv

      - name: Check for changes
        id: changes
        run: |
          echo "Changes detected in repository"
          echo "::set-output name=changed::true"

      - name: Store Repository Structure in MongoDB
        if: steps.changes.outputs.changed == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        run: |
          python store_repo_structure.py

      - name: Notify on completion
        if: always()
        run: |
          echo "Repository structure update completed"
